app/routes/main_bp.py
from flask import Blueprint, render_template
from app.models import db, Product

main_bp = Blueprint("main", __name__)


@main_bp.route("/")
def index():
    products = Product.query.all()
    return render_template("index.html", title="Main Page", product_list=products)


def group_options_by_type(options, option_type):
    return [option for option in options if option.type == option_type]


def group_options(options):
    option_types = ["slice", "wrap", "addition"]
    return {
        option_type: group_options_by_type(options, option_type)
        for option_type in option_types
    }


@main_bp.route("/order_product/<int:id>", methods=["GET"])
def order_product_modal(id: int):
    product = Product.query.get(id)
    if not product:
        return f"Product not found for id: {id}", 404
    grouped_options = group_options(product.available_options)

    return render_template(
        "modal/order_product.html", product=product, grouped_options=grouped_options
    )

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Order Management
      {% endblock title %}
    </title>
    <!-- Materialize CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
          rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="../static/css/styles.css" />
  </head>
  <body>
    <!-- Sidebar -->
    <nav class="nav-extended">
      <div class="nav-wrapper">
        <a href="/admin" class="waves-effect waves-light">
          <i class="material-icons admin-button">settings</i>
        </a>
        <a href="/" class="brand-logo center" id="nav-title">
          {% block logo %}
            직원용
          {% endblock logo %}
        </a>
      </div>
      {% block nav_content %}
      {% endblock nav_content %}
    </nav>
    <!-- Main Content -->
    <main>
      <div class="container" id="content">
        {% block content %}
          <div class="header-container">
            <span class="flow-text">Product Order</span>
          </div>
          <div class="divider"></div>
          <div class="card-container">
            {% for item in product_list %}
              {% with target_modal = url_for("main.order_product_modal", id=item.product_id) %}
                {% include "components/card.html" %}
              {% endwith %}
            {% endfor %}
          </div>
          <div id="modal_container"></div>
          <script src="{{ url_for('static', filename='js/order.js') }}"></script>
          <script src="{{ url_for('static', filename='js/modal.js') }}"></script>
        {% endblock content %}
      </div>
    </main>
    <!-- Materialize JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Index Page JavaScript -->
    <script src="../static/js/index.js"></script>
  </body>
</html>